amcl:
  ros__parameters:
    use_sim_time: false

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: ""   # SLAM모드라면 비워둠(별도 map 필요시 입력)

# 이 부분이 Navigation2 핵심
# 만약 SLAM모드라면 slam: True 옵션과 함께 사용, /map topic 활용
nav2_controller:
  ros__parameters:
    use_sim_time: false

nav2_planner:
  ros__parameters:
    use_sim_time: false

nav2_recoveries:
  ros__parameters:
    use_sim_time: false

bt_navigator:
  ros__parameters:
    use_sim_time: false

waypoint_follower:
  ros__parameters:
    use_sim_time: false

# TF 등 공통 설정
lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names:
      - "map_server"
      - "amcl"
      - "planner_server"
      - "controller_server"
      - "recoveries_server"
      - "bt_navigator"
      - "waypoint_follower"

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: true
      min_vel_x: 0.0
      max_vel_x: 0.26
      min_vel_y: 0.0
      max_vel_y: 0.0
      max_vel_theta: 1.0
      min_speed_xy: 0.0
      max_speed_xy: 0.26
      acc_lim_x: 2.5
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_theta: -3.2
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.5
      linear_granularity: 0.05
      angular_granularity: 0.025
      goal_distance_bias: 24.0
      path_distance_bias: 32.0
      occdist_scale: 0.01
      forward_point_distance: 0.325
      stop_time_buffer: 0.2
      scaling_speed: 0.25
      max_scaling_factor: 0.2
      # 가장 중요한 critic list!
      critics: ["GoalAlignCritic", "PathAlignCritic", "PathDistCritic", "GoalDistCritic", "ObstacleFootprintCritic"]
      GoalAlignCritic:
        scale: 24.0
      PathAlignCritic:
        scale: 32.0
      PathDistCritic:
        scale: 32.0
      GoalDistCritic:
        scale: 24.0
      ObstacleFootprintCritic:
        scale: 0.01

# costmap (장애물맵) 최소 설정
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      footprint: "[[0.2, 0.2], [0.2, -0.2], [-0.2, -0.2], [-0.2, 0.2]]"
      robot_radius: 0.2
      resolution: 0.05
      publish_frequency: 1.0
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      footprint: "[[0.2, 0.2], [0.2, -0.2], [-0.2, -0.2], [-0.2, 0.2]]"
      robot_radius: 0.2
      resolution: 0.05
      publish_frequency: 5.0
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"

# sensor topics 설정
# 실제 사용 환경에 맞게 센서 토픽명을 바꿔야 할 수 있음

